# Generated by Django 4.2.2 on 2023-07-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_bids_category_comments_listings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="label",
        ),
        migrations.RenameField(
            model_name="listings",
            old_name="image_links",
            new_name="image_url",
        ),
        migrations.RenameField(
            model_name="listings",
            old_name="name",
            new_name="title",
        ),
    ]
