# Generated by Django 4.2.2 on 2023-07-01 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_watchlist_rename_name_category_label_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Watchlist",
        ),
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="listings",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="image_url",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
