# Generated by Django 4.2.2 on 2023-07-01 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_delete_watchlist_category_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
