# Generated by Django 4.2.2 on 2023-07-01 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_remove_listings_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
