# Generated by Django 4.2.2 on 2023-07-03 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_listings_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="auctions.listings",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="message",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
