# Generated by Django 4.2.3 on 2023-07-05 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_bids_bid_bids_buyer_alter_listings_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bids",
            new_name="Bid",
        ),
    ]
