# Generated by Django 4.2.3 on 2023-07-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_bid_date_bid_listing_comments_date_listings_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
